{{ $fullname := include "event-source.fullname" . }}
{{ $labels := include "event-source.labels" . }}
{{- range $.Values.events }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullname }}-{{ .name }}
  labels:
    cronjob: {{ .name }}
    {{- $labels | nindent 4 }}
spec:
  schedule: {{ quote .schedule }}
  successfulJobsHistoryLimit: {{ default 10 $.Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 10 $.Values.failedJobsHistoryLimit }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ $fullname }}-{{ .name }}
          {{- with $.Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}        
          labels:
            cronjob: {{ .name }}
            {{- $labels | nindent 12 }}
        spec:
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          restartPolicy: OnFailure
          containers:
          - name: brigade-cron-event-source
            securityContext:
              {{- toYaml $.Values.securityContext | nindent 14 }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
            imagePullPolicy: {{ default "IfNotPresent" $.Values.image.pullPolicy }}
            env:
            - name: API_ADDRESS
              value: {{ $.Values.brigade.apiAddress }}
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}
                  key: brigadeAPIToken
            - name: API_IGNORE_CERT_WARNINGS
              value: {{ quote $.Values.brigade.apiIgnoreCertWarnings }}
            volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true  
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          volumes:
          - name: config
            configMap:
              name: {{ $fullname }}-{{ .name }}
--- 
{{- end }}
